export { default as Navbar } from './Navbar'
export { default as Hero } from './Hero'
export { default as Hero1 } from './Hero1'
export { default as ImgBackground } from './ImgBackground'
export { default as ServicesSection } from './ServicesSection'
export { default as ScrollToTop } from './ScrollToTop'
export { default as QualitySection } from './QualitySection'
export { default as Projects } from './Projects'
export { default as ProjectDetailImg } from './ProjectDetailImg'
export { default as ProjectDetailSection } from './ProjectDetailSection'
export { default as GallerySection2 } from './GallerySection2'
export { default as ContactComponent } from './ContactComponent'
export { default as Footer } from './Footer'

